// Complete translation packs for pa/bn/mr/gu/ta/te/kn/ml — merged by I18n.addTranslations.
window.I18N_LANG_PACKS = {
  pa: {
    nav_dashboard: 'ਡੈਸ਼ਬੋਰਡ', nav_scanner: 'ਸਕੈਨਰ', nav_history: 'ਇਤਿਹਾਸ', nav_howitworks: 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ', nav_about: 'ਸਾਡੇ ਬਾਰੇ', nav_settings: 'ਸੈਟਿੰਗਾਂ',
    hero_headline_1: 'ਘੋਟਾਲੇ ਨੂੰ', hero_headline_2: 'ਕਲਿੱਕ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਰੋਕੋ', hero_subtitle: 'ScamShield AI ਸੁਨੇਹਿਆਂ, ਸਕ੍ਰੀਨਸ਼ਾਟਾਂ, ਲਿੰਕਾਂ ਅਤੇ QR ਕੋਡਾਂ ਨੂੰ ਸਕੈਨ ਕਰਦਾ ਹੈ ਅਤੇ ਸਬੂਤਾਂ ਦੀ ਪੂਰੀ ਲੜੀ ਨਾਲ ਸਮਝਾਉਂਦਾ ਹੈ ਕਿ ਕੋਈ ਚੀਜ਼ ਧੋਖੇਬਾਜ਼ੀ ਕਿਉਂ ਹੈ।',
    hero_cta_scan: 'ਹੁਣੇ ਸਕੈਨ ਕਰੋ', hero_cta_protect: 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',
    stat_messages: 'ਸੁਨੇਹੇ ਜਾਂਚੇ ਗਏ', stat_accuracy: 'ਸਹੀ ਫੈਸਲਾ', stat_helpline: 'ਸਾਈਬਰ ਹੈਲਪਲਾਈਨ',
    trust_explainable: 'ਸਮਝਾਇਆ ਗਿਆ AI', trust_multilingual: '11 ਭਾਸ਼ਾਵਾਂ', trust_privacy: 'ਪਹਿਲਾਂ ਪਰਦੇਦਾਰੀ', trust_multimodal: '4 ਇਨਪੁਟ ਕਿਸਮਾਂ',
    scan_message: 'ਸੁਨੇਹਾ', scan_message_desc: 'ਸ਼ੱਕੀ WhatsApp ਸੁਨੇਹਾ, SMS ਜਾਂ ਈਮੇਲ ਪੇਸਟ ਕਰੋ', scan_screenshot: 'ਸਕ੍ਰੀਨਸ਼ਾਟ', scan_screenshot_desc: 'ਚੈਟ ਦੀ ਸਕ੍ਰੀਨਸ਼ਾਟ ਅਪਲੋਡ ਕਰੋ', scan_url: 'URL ਲਿੰਕ', scan_url_desc: 'ਸ਼ੱਕੀ ਲਿੰਕ ਦੀ ਜਾਂਚ ਕਰੋ', scan_qr: 'QR ਕੋਡ', scan_qr_desc: 'QR ਕੋਡ ਸਕੈਨ ਕਰਕੇ ਪੇਲੋਡ ਵੇਖੋ',
    analyze_btn: 'ਖ਼ਤਰੇ ਦੇ ਸੰਕੇਤਾਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ', analyzing: 'ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ...', error_empty_input: 'ਕਿਰਪਾ ਕਰਕੇ ਵਿਸ਼ਲੇਸ਼ਣ ਲਈ ਸਮੱਗਰੀ ਦਿਓ',
    verdict_safe: 'ਸੁਰੱਖਿਅਤ', verdict_suspicious: 'ਸ਼ੱਕੀ', verdict_dangerous: 'ਖ਼ਤਰਨਾਕ', verdict_critical: 'ਬਹੁਤ ਖ਼ਤਰਨਾਕ',
    risk_score: 'ਜੋਖਮ ਸਕੋਰ', threat_signals: 'ਖ਼ਤਰੇ ਦੇ ਸੰਕੇਤ', ai_analysis: 'AI ਵਿਸ਼ਲੇਸ਼ਣ', recommended_action: 'ਸਿਫ਼ਾਰਿਸ਼ ਕੀਤੀ ਕਾਰਵਾਈ',
    dash_title: 'ਸੁਰੱਖਿਆ ਡੈਸ਼ਬੋਰਡ', dash_total_scans: 'ਕੁੱਲ ਸਕੈਨ', dash_threats_blocked: 'ਰੋਕੇ ਗਏ ਖ਼ਤਰੇ', dash_critical: 'ਗੰਭੀਰ ਚੇਤਾਵਨੀਆਂ', dash_recent: 'ਹਾਲੀਆ ਗਤੀਵਿਧੀ', dash_no_scans: 'ਹਾਲੇ ਕੋਈ ਸਕੈਨ ਨਹੀਂ। ਸਕੈਨਰ ਨਾਲ ਸ਼ੁਰੂ ਕਰੋ।',
    history_title: 'ਸਕੈਨ ਇਤਿਹਾਸ', history_empty: 'ਕੋਈ ਇਤਿਹਾਸ ਨਹੀਂ', history_clear: 'ਇਤਿਹਾਸ ਸਾਫ਼ ਕਰੋ', btn_clear_history: 'ਇਤਿਹਾਸ ਸਾਫ਼ ਕਰੋ',
    settings_title: 'ਸੈਟਿੰਗਾਂ', settings_appearance: 'ਦਿੱਖ', settings_language: 'ਭਾਸ਼ਾ', settings_accessibility: 'ਪਹੁੰਚਯੋਗਤਾ', settings_reduced_motion: 'ਘਟੀ ਹੋਈ ਗਤੀ', settings_larger_text: 'ਵੱਡਾ ਟੈਕਸਟ', settings_privacy: 'ਪਰਦੇਦਾਰੀ ਅਤੇ ਡਾਟਾ', btn_clear_data: 'ਸਾਰਾ ਡਾਟਾ ਸਾਫ਼ ਕਰੋ',
    theme_light: 'ਲਾਈਟ', theme_dark: 'ਡਾਰਕ', theme_system: 'ਸਿਸਟਮ',
    toast_history_cleared: 'ਇਤਿਹਾਸ ਸਾਫ਼ ਹੋ ਗਿਆ', toast_data_cleared: 'ਸਾਰਾ ਡਾਟਾ ਸਾਫ਼ ਹੋ ਗਿਆ', cancel: 'ਰੱਦ ਕਰੋ', confirm: 'ਪੁਸ਼ਟੀ ਕਰੋ', close: 'ਬੰਦ ਕਰੋ',
    confirm_clear_data: 'ਕੀ ਤੁਸੀਂ ਯਕੀਨੀ ਤੌਰ \'ਤੇ ਸਾਰਾ ਡਾਟਾ ਸਾਫ਼ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ? ਇਸਨੂੰ ਵਾਪਸ ਨਹੀਂ ਕੀਤਾ ਜਾ ਸਕਦਾ।',
    agent_tab: 'ਏਜੰਟ ਸ਼ੀਲਡ', agent_hint: 'ਕਿਸੇ ਵੀ ਫਾਈਲ ਨੂੰ ਪੇਸਟ ਕਰੋ ਜੋ ਤੁਹਾਡਾ AI ਏਜੰਟ ਪੜ੍ਹੇਗਾ — ਪ੍ਰੋਂਪਟ ਇੰਜੈਕਸ਼ਨ, ਲੁਕਵੇਂ ਯੂਨੀਕੋਡ ਪੇਲੋਡ ਅਤੇ ਖ਼ਤਰਨਾਕ ਹੁੱਕਾਂ ਲਈ ਜਾਂਚ ਕਰੋ।', agent_clean: 'ਸਾਫ਼ — ਤੁਹਾਡੇ ਏਜੰਟ ਲਈ ਸੁਰੱਖਿਅਤ', agent_critical: 'ਗੰਭੀਰ — ਇਸ ਫਾਈਲ \'ਤੇ ਭਰੋਸਾ ਨਾ ਕਰੋ'
  },
  bn: {
    nav_dashboard: 'ড্যাশবোর্ড', nav_scanner: 'স্ক্যানার', nav_history: 'ইতিহাস', nav_howitworks: 'এটি কীভাবে কাজ করে', nav_about: 'আমাদের সম্পর্কে', nav_settings: 'সেটিংস',
    hero_headline_1: 'প্রতারণাকে', hero_headline_2: 'ক্লিকের আগেই থামান', hero_subtitle: 'ScamShield AI বার্তা, স্ক্রিনশট, লিঙ্ক ও QR কোড স্ক্যান করে এবং পূর্ণ প্রমাণের সাথে ব্যাখ্যা করে কেন কিছু প্রতারণা।',
    hero_cta_scan: 'এখনই স্ক্যান করুন', hero_cta_protect: 'এটি কীভাবে কাজ করে',
    stat_messages: 'বার্তা পরীক্ষিত', stat_accuracy: 'সঠিক রায়', stat_helpline: 'সাইবার হেল্পলাইন',
    trust_explainable: 'ব্যাখ্যাযোগ্য AI', trust_multilingual: '১১টি ভাষা', trust_privacy: 'প্রাইভেসি-ফার্স্ট', trust_multimodal: '৪ ধরনের ইনপুট',
    scan_message: 'বার্তা', scan_message_desc: 'সন্দেহজনক WhatsApp বার্তা, SMS বা ইমেল পেস্ট করুন', scan_screenshot: 'স্ক্রিনশট', scan_screenshot_desc: 'চ্যাটের স্ক্রিনশট আপলোড করুন', scan_url: 'URL লিঙ্ক', scan_url_desc: 'সন্দেহজনক লিঙ্ক পরীক্ষা করুন', scan_qr: 'QR কোড', scan_qr_desc: 'QR স্ক্যান করে পেলোড দেখুন',
    analyze_btn: 'হুমকি সংকেত বিশ্লেষণ করুন', analyzing: 'বিশ্লেষণ চলছে...', error_empty_input: 'বিশ্লেষণের জন্য কিছু দিন',
    verdict_safe: 'নিরাপদ', verdict_suspicious: 'সন্দেহজনক', verdict_dangerous: 'বিপজ্জনক', verdict_critical: 'অতি বিপজ্জনক',
    risk_score: 'ঝুঁকি স্কোর', threat_signals: 'হুমকির সংকেত', ai_analysis: 'AI বিশ্লেষণ', recommended_action: 'প্রস্তাবিত পদক্ষেপ',
    dash_title: 'সিকিউরিটি ড্যাশবোর্ড', dash_total_scans: 'মোট স্ক্যান', dash_threats_blocked: 'প্রতিহত হুমকি', dash_critical: 'জটিল সতর্কতা', dash_recent: 'সাম্প্রতিক কার্যক্রম', dash_no_scans: 'এখনও কোনো স্ক্যান নেই। স্ক্যানার দিয়ে শুরু করুন।',
    history_title: 'স্ক্যান ইতিহাস', history_empty: 'কোনো ইতিহাস নেই', history_clear: 'ইতিহাস মুছুন', btn_clear_history: 'ইতিহাস মুছুন',
    settings_title: 'সেটিংস', settings_appearance: 'অ্যাপিয়ারেন্স', settings_language: 'ভাষা', settings_accessibility: 'অ্যাক্সেসিবিলিটি', settings_reduced_motion: 'কম গতি', settings_larger_text: 'বড় লেখা', settings_privacy: 'প্রাইভেসি ও ডেটা', btn_clear_data: 'সব ডেটা মুছুন',
    theme_light: 'লাইট', theme_dark: 'ডার্ক', theme_system: 'সিস্টেম',
    toast_history_cleared: 'ইতিহাস মুছে ফেলা হয়েছে', toast_data_cleared: 'সব ডেটা মুছে ফেলা হয়েছে', cancel: 'বাতিল', confirm: 'নিশ্চিত', close: 'বন্ধ',
    confirm_clear_data: 'আপনি কি নিশ্চিতভাবে সব ডেটা মুছতে চান? এটি ফেরানো যাবে না।',
    agent_tab: 'এজেন্ট শিল্ড', agent_hint: 'AI এজেন্ট যে ফাইল পড়বে তা পেস্ট করুন — প্রম্পট ইনজেকশন, অদৃশ্য ইউনিকোড পেলোড ও বিপজ্জনক হুক পরীক্ষা হয়।', agent_clean: 'পরিষ্কার — আপনার এজেন্টের জন্য নিরাপদ', agent_critical: 'জটিল — এই ফাইলে বিশ্বাস করবেন না'
  },
  mr: {
    nav_dashboard: 'डॅशबोर्ड', nav_scanner: 'स्कॅनर', nav_history: 'इतिहास', nav_howitworks: 'हे कसे कार्य करते', nav_about: 'आमच्याबद्दल', nav_settings: 'सेटिंग्ज',
    hero_headline_1: 'घोटाळा', hero_headline_2: 'क्लिक करण्यापूर्वी थांबवा', hero_subtitle: 'ScamShield AI संदेश, स्क्रीनशॉट, लिंक आणि QR कोड स्कॅन करते आणि पूर्ण पुराव्यासह स्पष्ट करते की काही गैरवर्तन का आहे.',
    hero_cta_scan: 'आता स्कॅन करा', hero_cta_protect: 'हे कसे कार्य करते',
    stat_messages: 'संदेश तपासले', stat_accuracy: 'अचूक निकाल', stat_helpline: 'सायबर हेल्पलाइन',
    trust_explainable: 'स्पष्टीकरणक्षम AI', trust_multilingual: '११ भाषा', trust_privacy: 'प्रायव्हसी-प्रथम', trust_multimodal: '४ इनपुट प्रकार',
    scan_message: 'संदेश', scan_message_desc: 'संशयास्पद WhatsApp संदेश, SMS किंवा ईमेल पेस्ट करा', scan_screenshot: 'स्क्रीनशॉट', scan_screenshot_desc: 'चॅटचे स्क्रीनशॉट अपलोड करा', scan_url: 'URL लिंक', scan_url_desc: 'संशयास्पद लिंक तपासा', scan_qr: 'QR कोड', scan_qr_desc: 'QR स्कॅन करा आणि पेलोड पहा',
    analyze_btn: 'धोक्याची चिन्हे विश्लेषित करा', analyzing: 'विश्लेषण सुरू...', error_empty_input: 'विश्लेषणासाठी मजकूर द्या',
    verdict_safe: 'सुरक्षित', verdict_suspicious: 'संशयास्पद', verdict_dangerous: 'धोकादायक', verdict_critical: 'अत्यंत धोकादायक',
    risk_score: 'धोका गुण', threat_signals: 'धोक्याची चिन्हे', ai_analysis: 'AI विश्लेषण', recommended_action: 'शिफारस केलेली कृती',
    dash_title: 'सिक्युरिटी डॅशबोर्ड', dash_total_scans: 'एकूण स्कॅन', dash_threats_blocked: 'अडवलेले धोके', dash_critical: 'गंभीर सूचना', dash_recent: 'अलीकडील क्रियाकलाप', dash_no_scans: 'अजून स्कॅन नाही. स्कॅनरने सुरुवात करा.',
    history_title: 'स्कॅन इतिहास', history_empty: 'इतिहास नाही', history_clear: 'इतिहास पुसा', btn_clear_history: 'इतिहास पुसा',
    settings_title: 'सेटिंग्ज', settings_appearance: 'दिसणे', settings_language: 'भाषा', settings_accessibility: 'सुलभता', settings_reduced_motion: 'कमी गती', settings_larger_text: 'मोठा मजकूर', settings_privacy: 'प्रायव्हसी आणि डेटा', btn_clear_data: 'सर्व डेटा पुसा',
    theme_light: 'लाइट', theme_dark: 'डार्क', theme_system: 'सिस्टम',
    toast_history_cleared: 'इतिहास पुसला', toast_data_cleared: 'सर्व डेटा पुसला', cancel: 'रद्द', confirm: 'पुष्टी', close: 'बंद',
    confirm_clear_data: 'तुम्हाला खात्री आहे सर्व डेटा पुसायचा आहे? हे परत आणता येणार नाही.',
    agent_tab: 'एजंट शील्ड', agent_hint: 'तुमचा AI एजंट जो फाइल वाचेल ती पेस्ट करा — प्रॉम्प्ट इंजेक्शन, अदृश्य युनिकोड पेलोड आणि धोकादायक हूक तपासले जातात.', agent_clean: 'स्वच्छ — तुमच्या एजंटसाठी सुरक्षित', agent_critical: 'गंभीर — या फाइलवर विश्वासू ठेवू नका'
  },
  gu: {
    nav_dashboard: 'ડેશબોર્ડ', nav_scanner: 'સ્કેનર', nav_history: 'ઇતિહાસ', nav_howitworks: 'આ કેવી રીતે કામ કરે છે', nav_about: 'અમારા વિશે', nav_settings: 'સેટિંગ્સ',
    hero_headline_1: 'છેતરપિંડીને', hero_headline_2: 'ક્લિક કરતાં પહેલાં રોકો', hero_subtitle: 'ScamShield AI સંદેશા, સ્ક્રીનશોટ, લિંક અને QR કોડ સ્કેન કરે છે અને પૂરા પુરાવા સાથે સમજાવે છે કે કંઈક છેતરપિંડી કેમ છે.',
    hero_cta_scan: 'હવે સ્કેન કરો', hero_cta_protect: 'આ કેવી રીતે કામ કરે છે',
    stat_messages: 'સંદેશા તપાસ્યા', stat_accuracy: 'સચોટ ચુકાદો', stat_helpline: 'સાયબર હેલ્પલાઇન',
    trust_explainable: 'સમજૂતીયોગ્ય AI', trust_multilingual: '૧૧ ભાષાઓ', trust_privacy: 'પ્રાઇવસી-ફર્સ્ટ', trust_multimodal: '૪ ઇનપુટ પ્રકારો',
    scan_message: 'સંદેશ', scan_message_desc: 'શંકાસ્પદ WhatsApp સંદેશ, SMS અથવા ઈમેલ પેસ્ટ કરો', scan_screenshot: 'સ્ક્રીનશોટ', scan_screenshot_desc: 'ચેટનો સ્ક્રીનશોટ અપલોડ કરો', scan_url: 'URL લિંક', scan_url_desc: 'શંકાસ્પદ લિંક તપાસો', scan_qr: 'QR કોડ', scan_qr_desc: 'QR સ્કેન કરીને પેલોડ જુઓ',
    analyze_btn: 'ધમકી સંકેતોનું વિશ્લેષણ કરો', analyzing: 'વિશ્લેષણ થઈ રહ્યું છે...', error_empty_input: 'વિશ્લેષણ માટે સામગ્રી આપો',
    verdict_safe: 'સુરક્ષિત', verdict_suspicious: 'શંકાસ્પદ', verdict_dangerous: 'ખતરનાક', verdict_critical: 'અત્યંત ખતરનાક',
    risk_score: 'જોખમ સ્કોર', threat_signals: 'ધમકી સંકેતો', ai_analysis: 'AI વિશ્લેષણ', recommended_action: 'સૂચવેલી ક્રિયા',
    dash_title: 'સિક્યોરિટી ડેશબોર્ડ', dash_total_scans: 'કુલ સ્કેન', dash_threats_blocked: 'અટકાવેલા ધમકીઓ', dash_critical: 'ગંભીર ચેતવણીઓ', dash_recent: 'તાજી પ્રવૃત્તિ', dash_no_scans: 'હજી કોઈ સ્કેન નથી. સ્કેનરથી શરૂ કરો.',
    history_title: 'સ્કેન ઇતિહાસ', history_empty: 'કોઈ ઇતિહાસ નથી', history_clear: 'ઇતિહાસ સાફ કરો', btn_clear_history: 'ઇતિહાસ સાફ કરો',
    settings_title: 'સેટિંગ્સ', settings_appearance: 'દેખાવ', settings_language: 'ભાષા', settings_accessibility: 'સુલભતા', settings_reduced_motion: 'ઘટાડેલી ગતિ', settings_larger_text: 'મોટું લખાણ', settings_privacy: 'પ્રાઇવસી અને ડેટા', btn_clear_data: 'બધો ડેટા સાફ કરો',
    theme_light: 'લાઇટ', theme_dark: 'ડાર્ક', theme_system: 'સિસ્ટમ',
    toast_history_cleared: 'ઇતિહાસ સાફ થયો', toast_data_cleared: 'બધો ડેટા સાફ થયો', cancel: 'રદ', confirm: 'પુષ્ટિ', close: 'બંધ',
    confirm_clear_data: 'શું તમે ખરેખર બધો ડેટા સાફ કરવા માંગો છો? આ પાછું લાવી શકાય નહીં.',
    agent_tab: 'એજન્ટ શીલ્ડ', agent_hint: 'તમારો AI એજન્ટ જે ફાઇલ વાંચશે તે પેસ્ટ કરો — પ્રોમ્પ્ટ ઇન્જેક્શન, અદ્રશ્ય યુનિકોડ પેલોડ અને ખતરનાક હૂક્સ તપાસાય છે.', agent_clean: 'સાફ — તમારા એજન્ટ માટે સુરક્ષિત', agent_critical: 'ગંભીર — આ ફાઇલ પર વિશ્વાસ કરો નહીં'
  },
  ta: {
    nav_dashboard: 'டாஷ்போர்டு', nav_scanner: 'ஸ்கேனர்', nav_history: 'வரலாறு', nav_howitworks: 'இது எப்படி வேலை செய்கிறது', nav_about: 'எங்களை பற்றி', nav_settings: 'அமைப்புகள்',
    hero_headline_1: 'மோசடியை', hero_headline_2: 'கிளிக் செய்வதற்கு முன் நிறுத்து', hero_subtitle: 'ScamShield AI செய்திகள், ஸ்கிரீன்ஷாட்கள், இணைப்புகள் மற்றும் QR குறியீடுகளை ஸ்கேன் செய்து முழு ஆதாரத் தொடருடன் ஏன் ஏதோ மோசடி என்பதை விளக்குகிறது.',
    hero_cta_scan: 'இப்போது ஸ்கேன் செய்', hero_cta_protect: 'இது எப்படி வேலை செய்கிறது',
    stat_messages: 'செய்திகள் பரிசோதிக்கப்பட்டன', stat_accuracy: 'துல்லியமான தீர்ப்பு', stat_helpline: 'சைபர் உதவி எண்',
    trust_explainable: 'விளக்கக்கூடிய AI', trust_multilingual: '11 மொழிகள்', trust_privacy: 'தனியுரிமை முதன்மை', trust_multimodal: '4 உள்ளீட்டு வகைகள்',
    scan_message: 'செய்தி', scan_message_desc: 'சந்தேகத்திற்குரிய WhatsApp செய்தி, SMS அல்லது மின்னஞ்சலை ஒட்டவும்', scan_screenshot: 'ஸ்கிரீன்ஷாட்', scan_screenshot_desc: 'அரட்டையின் ஸ்கிரீன்ஷாட்டை பதிவேற்றவும்', scan_url: 'URL இணைப்பு', scan_url_desc: 'சந்தேகத்திற்குரிய இணைப்பை சோதிக்கவும்', scan_qr: 'QR குறியீடு', scan_qr_desc: 'QR ஸ்கேன் செய்து பேலோடைப் பார்க்கவும்',
    analyze_btn: 'அச்சுறுத்தல் அறிகுறிகளை பகுப்பாய்வு செய்', analyzing: 'பகுப்பாய்வு நடக்கிறது...', error_empty_input: 'பகுப்பாய்வுக்கு உள்ளடக்கத்தை வழங்கவும்',
    verdict_safe: 'பாதுகாப்பு', verdict_suspicious: 'சந்தேகத்திற்குரியது', verdict_dangerous: 'ஆபத்தானது', verdict_critical: 'மிக ஆபத்தானது',
    risk_score: 'ஆபத்து மதிப்பெண்', threat_signals: 'அச்சுறுத்தல் அறிகுறிகள்', ai_analysis: 'AI பகுப்பாய்வு', recommended_action: 'பரிந்துரைக்கப்பட்ட செயல்',
    dash_title: 'பாதுகாப்பு டாஷ்போர்டு', dash_total_scans: 'மொத்த ஸ்கேன்கள்', dash_threats_blocked: 'தடுக்கப்பட்ட அச்சுறுத்தல்கள்', dash_critical: 'முக்கிய எச்சரிக்கைகள்', dash_recent: 'சமீபத்திய செயல்பாடு', dash_no_scans: 'இன்னும் ஸ்கேன் இல்லை. ஸ்கேனரில் தொடங்குங்கள்.',
    history_title: 'ஸ்கேன் வரலாறு', history_empty: 'வரலாறு இல்லை', history_clear: 'வரலாற்றை அழி', btn_clear_history: 'வரலாற்றை அழி',
    settings_title: 'அமைப்புகள்', settings_appearance: 'தோற்றம்', settings_language: 'மொழி', settings_accessibility: 'அணுகல்தன்மை', settings_reduced_motion: 'குறைந்த அசைவு', settings_larger_text: 'பெரிய எழுத்து', settings_privacy: 'தனியுரிமை மற்றும் தரவு', btn_clear_data: 'எல்லா தரவையும் அழி',
    theme_light: 'லைட்', theme_dark: 'டார்க்', theme_system: 'சிஸ்டம்',
    toast_history_cleared: 'வரலாறு அழிக்கப்பட்டது', toast_data_cleared: 'எல்லா தரவும் அழிக்கப்பட்டது', cancel: 'ரத்து', confirm: 'உறுதிப்படுத்து', close: 'மூடு',
    confirm_clear_data: 'எல்லா தரவையும் அழிக்க விரும்புகிறீர்களா? இதை மீட்டெடுக்க முடியாது.',
    agent_tab: 'ஏஜெண்ட் ஷீல்ட்', agent_hint: 'உங்கள் AI ஏஜென்ட் படிக்கும் எந்த கோப்பையும் ஒட்டவும் — ப்ராம்ப்ட் ஊசி, கண்ணுக்குத் தெரியாத யூனிகோட் பேலோடு மற்றும் ஆபத்தான ஹூக்குகள் சோதிக்கப்படுகின்றன.', agent_clean: 'சுத்தமான — உங்கள் ஏஜென்டுக்கு பாதுகாப்பு', agent_critical: 'மிக ஆபத்தானது — இந்த கோப்பை நம்ப வேண்டாம்'
  },
  te: {
    nav_dashboard: 'డాష్‌బోర్డ్', nav_scanner: 'స్కానర్', nav_history: 'చరిత్ర', nav_howitworks: 'ఇది ఎలా పనిచేస్తుంది', nav_about: 'మా గురించి', nav_settings: 'సెట్టింగ్‌లు',
    hero_headline_1: 'మోసాన్ని', hero_headline_2: 'క్లిక్ చేసే ముందే ఆపండి', hero_subtitle: 'ScamShield AI సందేశాలు, స్క్రీన్‌షాట్‌లు, లింక్‌లు మరియు QR కోడ్‌లను స్కాన్ చేసి పూర్తి సాక్ష్య శృంఖలతో ఏదైనా మోసం ఎందుకు అని వివరిస్తుంది.',
    hero_cta_scan: 'ఇప్పుడే స్కాన్ చేయండి', hero_cta_protect: 'ఇది ఎలా పనిచేస్తుంది',
    stat_messages: 'సందేశాలు తనిఖీ అయ్యాయి', stat_accuracy: 'ఖచ్చితమైన తీర్పు', stat_helpline: 'సైబర్ హెల్ప్‌లైన్',
    trust_explainable: 'వివరించగల AI', trust_multilingual: '11 భాషలు', trust_privacy: 'గోప్యత ముందు', trust_multimodal: '4 ఇన్‌పుట్ రకాలు',
    scan_message: 'సందేశం', scan_message_desc: 'అనుమానాస్పద WhatsApp సందేశం, SMS లేదా ఇమెయిల్ పేస్ట్ చేయండి', scan_screenshot: 'స్క్రీన్‌షాట్', scan_screenshot_desc: 'చాట్ స్క్రీన్‌షాట్ అప్‌లోడ్ చేయండి', scan_url: 'URL లింక్', scan_url_desc: 'అనుమానాస్పద లింక్ తనిఖీ చేయండి', scan_qr: 'QR కోడ్', scan_qr_desc: 'QR స్కాన్ చేసి పేలోడ్ చూడండి',
    analyze_btn: 'బెదిరింపు సంకేతాలను విశ్లేషించండి', analyzing: 'విశ్లేషణ జరుగుతోంది...', error_empty_input: 'విశ్లేషణకు కంటెంట్ ఇవ్వండి',
    verdict_safe: 'సురక్షితం', verdict_suspicious: 'అనుమానాస్పదం', verdict_dangerous: 'ప్రమాదకరం', verdict_critical: 'అత్యంత ప్రమాదకరం',
    risk_score: 'ప్రమాద స్కోరు', threat_signals: 'బెదిరింపు సంకేతాలు', ai_analysis: 'AI విశ్లేషణ', recommended_action: 'సిఫార్సు చేసిన చర్య',
    dash_title: 'సెక్యూరిటీ డాష్‌బోర్డ్', dash_total_scans: 'మొత్తం స్కాన్‌లు', dash_threats_blocked: 'అడ్డుకున్న బెదిరింపులు', dash_critical: 'క్లిష్ట హెచ్చరికలు', dash_recent: 'ఇటీవలి కార్యాచరణ', dash_no_scans: 'ఇంకా స్కాన్లు లేవు. స్కానర్‌తో మొదలుపెట్టండి.',
    history_title: 'స్కాన్ చరిత్ర', history_empty: 'చరిత్ర లేదు', history_clear: 'చరిత్రను క్లియర్ చేయండి', btn_clear_history: 'చరిత్రను క్లియర్ చేయండి',
    settings_title: 'సెట్టింగ్‌లు', settings_appearance: 'రూపం', settings_language: 'భాష', settings_accessibility: 'ప్రవేశసామర్థ్యం', settings_reduced_motion: 'తక్కువ కదలిక', settings_larger_text: 'పెద్ద టెక్స్ట్', settings_privacy: 'గోప్యత మరియు డేటా', btn_clear_data: 'అన్ని డేటా క్లియర్ చేయండి',
    theme_light: 'లైట్', theme_dark: 'డార్క్', theme_system: 'సిస్టమ్',
    toast_history_cleared: 'చరిత్ర క్లియర్ అయింది', toast_data_cleared: 'అన్ని డేటా క్లియర్ అయింది', cancel: 'రద్దు', confirm: 'నిర్ధారించు', close: 'మూసివేయి',
    confirm_clear_data: 'మీరు ఖచ్చితంగా అన్ని డేటా క్లియర్ చేయాలనుకుంటున్నారా? ఇది తిరిగి రాదు.',
    agent_tab: 'ఏజెంట్ షీల్డ్', agent_hint: 'మీ AI ఏజెంట్ చదివే ఏ ఫైల్‌నైనా పేస్ట్ చేయండి — ప్రాంప్ట్ ఇంజెక్షన్, అదృశ్య యూనికోడ్ పేలోడ్ మరియు ప్రమాదకర హుక్‌లు తనిఖీ అవుతాయి.', agent_clean: 'శుభ్రం — మీ ఏజెంట్‌కు సురక్షితం', agent_critical: 'అత్యంత ప్రమాదకరం — ఈ ఫైల్‌ను నమ్మకండి'
  },
  kn: {
    nav_dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', nav_scanner: 'ಸ್ಕ್ಯಾನರ್', nav_history: 'ಇತಿಹಾಸ', nav_howitworks: 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ', nav_about: 'ನಮ್ಮ ಬಗ್ಗೆ', nav_settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    hero_headline_1: 'ವಂಚನೆಯನ್ನು', hero_headline_2: 'ಕ್ಲಿಕ್ ಮಾಡುವ ಮೊದಲೇ ತಡೆಯಿರಿ', hero_subtitle: 'ScamShield AI ಸಂದೇಶಗಳು, ಸ್ಕ್ರೀನ್‌ಶಾಟ್‌ಗಳು, ಲಿಂಕ್‌ಗಳು ಮತ್ತು QR ಕೋಡ್‌ಗಳನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ಪೂರ್ಣ ಸಾಕ್ಷಿ ಸರಪಳಿಯೊಂದಿಗೆ ಏಕೆ ವಂಚನೆ ಎಂದು ವಿವರಿಸುತ್ತದೆ.',
    hero_cta_scan: 'ಈಗ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ', hero_cta_protect: 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
    stat_messages: 'ಸಂದೇಶಗಳು ಪರಿಶೀಲಿತ', stat_accuracy: 'ನಿಖರ ತೀರ್ಪು', stat_helpline: 'ಸೈಬರ್ ಸಹಾಯವಾಣಿ',
    trust_explainable: 'ವಿವರಿಸಬಲ್ಲ AI', trust_multilingual: '11 ಭಾಷೆಗಳು', trust_privacy: 'ಗೋಪ್ಯತೆ ಮೊದಲು', trust_multimodal: '4 ಇನ್‌ಪುಟ್ ವಿಧಗಳು',
    scan_message: 'ಸಂದೇಶ', scan_message_desc: 'ಅನುಮಾನಾಸ್ಪದ WhatsApp ಸಂದೇಶ, SMS ಅಥವಾ ಇಮೇಲ್ ಅಂಟಿಸಿ', scan_screenshot: 'ಸ್ಕ್ರೀನ್‌ಶಾಟ್', scan_screenshot_desc: 'ಚಾಟ್‌ನ ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ', scan_url: 'URL ಲಿಂಕ್', scan_url_desc: 'ಅನುಮಾನಾಸ್ಪದ ಲಿಂಕ್ ಪರಿಶೀಲಿಸಿ', scan_qr: 'QR ಕೋಡ್', scan_qr_desc: 'QR ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ಪೇಲೋಡ್ ನೋಡಿ',
    analyze_btn: 'ಬೆದರಿಕೆ ಸಂಕೇತಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಿ', analyzing: 'ವಿಶ್ಲೇಷಣೆ ನಡೆಯುತ್ತಿದೆ...', error_empty_input: 'ವಿಶ್ಲೇಷಣೆಗೆ ವಿಷಯವನ್ನು ನೀಡಿ',
    verdict_safe: 'ಸುರಕ್ಷಿತ', verdict_suspicious: 'ಅನುಮಾನಾಸ್ಪದ', verdict_dangerous: 'ಅಪಾಯಕಾರಿ', verdict_critical: 'ಅತ್ಯಂತ ಅಪಾಯಕಾರಿ',
    risk_score: 'ಅಪಾಯ ಅಂಕ', threat_signals: 'ಬೆದರಿಕೆ ಸಂಕೇತಗಳು', ai_analysis: 'AI ವಿಶ್ಲೇಷಣೆ', recommended_action: 'ಶಿಫಾರಸು ಮಾಡಿದ ಕ್ರಿಯೆ',
    dash_title: 'ಸೆಕ್ಯುರಿಟಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', dash_total_scans: 'ಒಟ್ಟು ಸ್ಕ್ಯಾನ್‌ಗಳು', dash_threats_blocked: 'ತಡೆಹಿಡಿದ ಬೆದರಿಕೆಗಳು', dash_critical: 'ಗಂಭೀರ ಎಚ್ಚರಿಕೆಗಳು', dash_recent: 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ', dash_no_scans: 'ಇನ್ನೂ ಸ್ಕ್ಯಾನ್ ಇಲ್ಲ. ಸ್ಕ್ಯಾನರ್‌ನಿಂದ ಪ್ರಾರಂಭಿಸಿ.',
    history_title: 'ಸ್ಕ್ಯಾನ್ ಇತಿಹಾಸ', history_empty: 'ಇತಿಹಾಸ ಇಲ್ಲ', history_clear: 'ಇತಿಹಾಸ ತೆರವು', btn_clear_history: 'ಇತಿಹಾಸ ತೆರವು',
    settings_title: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು', settings_appearance: 'ನೋಟ', settings_language: 'ಭಾಷೆ', settings_accessibility: 'ಪ್ರವೇಶಿಸುವಿಕೆ', settings_reduced_motion: 'ಕಡಿಮೆ ಚಲನೆ', settings_larger_text: 'ದೊಡ್ಡ ಪಠ್ಯ', settings_privacy: 'ಗೋಪ್ಯತೆ ಮತ್ತು ಡೇಟಾ', btn_clear_data: 'ಎಲ್ಲಾ ಡೇಟಾ ತೆರವು',
    theme_light: 'ಲೈಟ್', theme_dark: 'ಡಾರ್ಕ್', theme_system: 'ಸಿಸ್ಟಮ್',
    toast_history_cleared: 'ಇತಿಹಾಸ ತೆರವಾಗಿದೆ', toast_data_cleared: 'ಎಲ್ಲಾ ಡೇಟಾ ತೆರವಾಗಿದೆ', cancel: 'ರದ್ದು', confirm: 'ದೃಢೀಕರಿಸು', close: 'ಮುಚ್ಚಿ',
    confirm_clear_data: 'ನೀವು ಖಚಿತವಾಗಿ ಎಲ್ಲಾ ಡೇಟಾ ತೆರವುಗೊಳಿಸಲು ಬಯಸುವಿರಾ? ಇದನ್ನು ಹಿಂತಿರುಗಿಸಲಾಗುವುದಿಲ್ಲ.',
    agent_tab: 'ಏಜೆಂಟ್ ಶೀಲ್ಡ್', agent_hint: 'ನಿಮ್ಮ AI ಏಜೆಂಟ್ ಓದುವ ಯಾವುದೇ ಫೈಲ್ ಅಂಟಿಸಿ — ಪ್ರಾಂಪ್ಟ್ ಇಂಜೆಕ್ಷನ್, ಅಗೋಚರ ಯುನಿಕೋಡ್ ಪೇಲೋಡ್ ಮತ್ತು ಅಪಾಯಕಾರಿ ಹುಕ್‌ಗಳು ಪರಿಶೀಲಿಸಲಾಗುತ್ತದೆ.', agent_clean: 'ಸ್ವಚ್ಛ — ನಿಮ್ಮ ಏಜೆಂಟ್‌ಗೆ ಸುರಕ್ಷಿತ', agent_critical: 'ಅತ್ಯಂತ ಅಪಾಯಕಾರಿ — ಈ ಫೈಲ್ ಅನ್ನು ನಂಬಬೇಡಿ'
  },
  ml: {
    nav_dashboard: 'ഡാഷ്ബോർഡ്', nav_scanner: 'സ്കാനർ', nav_history: 'ചരിത്രം', nav_howitworks: 'ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു', nav_about: 'ഞങ്ങളെക്കുറിച്ച്', nav_settings: 'സെറ്റിംഗ്സ്',
    hero_headline_1: 'തട്ടിപ്പിനെ', hero_headline_2: 'ക്ലിക്ക് ചെയ്യും മുമ്പേ തടയുക', hero_subtitle: 'ScamShield AI സന്ദേശങ്ങൾ, സ്ക്രീൻഷോട്ടുകൾ, ലിങ്കുകൾ, QR കോഡുകൾ എന്നിവ സ്കാൻ ചെയ്ത് പൂർണ്ണ തെളിവ് ശൃംഖലയോടെ എന്തുകൊണ്ട് തട്ടിപ്പാണെന്ന് വിശദീകരിക്കുന്നു.',
    hero_cta_scan: 'ഇപ്പോൾ സ്കാൻ ചെയ്യുക', hero_cta_protect: 'ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു',
    stat_messages: 'സന്ദേശങ്ങൾ പരിശോധിച്ചു', stat_accuracy: 'കൃത്യമായ വിധി', stat_helpline: 'സൈബർ ഹെൽപ്പ്‌ലൈൻ',
    trust_explainable: 'വിശദീകരിക്കാവുന്ന AI', trust_multilingual: '11 ഭാഷകൾ', trust_privacy: 'സ്വകാര്യത ആദ്യം', trust_multimodal: '4 ഇൻപുട്ട് തരങ്ങൾ',
    scan_message: 'സന്ദേശം', scan_message_desc: 'സംശയാസ്പദ WhatsApp സന്ദേശം, SMS അല്ലെങ്കിൽ ഇമെയിൽ പേസ്റ്റ് ചെയ്യുക', scan_screenshot: 'സ്ക്രീൻഷോട്ട്', scan_screenshot_desc: 'ചാറ്റിന്റെ സ്ക്രീൻഷോട്ട് അപ്‌ലോഡ് ചെയ്യുക', scan_url: 'URL ലിങ്ക്', scan_url_desc: 'സംശയാസ്പദ ലിങ്ക് പരിശോധിക്കുക', scan_qr: 'QR കോഡ്', scan_qr_desc: 'QR സ്കാൻ ചെയ്ത് പേലോഡ് കാണുക',
    analyze_btn: 'ഭീഷണി സൂചനകൾ വിശകലനം ചെയ്യുക', analyzing: 'വിശകലനം നടക്കുന്നു...', error_empty_input: 'വിശകലനത്തിന് ഉള്ളടക്കം നൽകുക',
    verdict_safe: 'സുരക്ഷിതം', verdict_suspicious: 'സംശയാസ്പദം', verdict_dangerous: 'അപകടകരം', verdict_critical: 'വളരെ അപകടകരം',
    risk_score: 'അപകട സ്കോർ', threat_signals: 'ഭീഷണി സൂചനകൾ', ai_analysis: 'AI വിശകലനം', recommended_action: 'ശിപാർശ ചെയ്ത നടപടി',
    dash_title: 'സെക്യൂരിറ്റി ഡാഷ്ബോർഡ്', dash_total_scans: 'ആകെ സ്കാനുകൾ', dash_threats_blocked: 'തടഞ്ഞ ഭീഷണികൾ', dash_critical: 'ഗുരുതര മുന്നറിയിപ്പുകൾ', dash_recent: 'സമീപകാല പ്രവർത്തനം', dash_no_scans: 'ഇതുവരെ സ്കാനുകൾ ഇല്ല. സ്കാനറിൽ ആരംഭിക്കുക.',
    history_title: 'സ്കാൻ ചരിത്രം', history_empty: 'ചരിത്രമില്ല', history_clear: 'ചരിത്രം മായ്ക്ക്', btn_clear_history: 'ചരിത്രം മായ്ക്ക്',
    settings_title: 'സെറ്റിംഗ്സ്', settings_appearance: 'രൂപഭാവം', settings_language: 'ഭാഷ', settings_accessibility: 'പ്രവേശനക്ഷമത', settings_reduced_motion: 'ചലനം കുറയ്ക്കുക', settings_larger_text: 'വലിയ ടെക്സ്റ്റ്', settings_privacy: 'സ്വകാര്യതയും ഡാറ്റയും', btn_clear_data: 'എല്ലാ ഡാറ്റയും മായ്ക്കുക',
    theme_light: 'ലൈറ്റ്', theme_dark: 'ഡാർക്ക്', theme_system: 'സിസ്റ്റം',
    toast_history_cleared: 'ചരിത്രം മായ്ച്ചു', toast_data_cleared: 'എല്ലാ ഡാറ്റയും മായ്ച്ചു', cancel: 'റദ്ദാക്കുക', confirm: 'സ്ഥിരീകരിക്കുക', close: 'അടയ്ക്കുക',
    confirm_clear_data: 'എല്ലാ ഡാറ്റയും മായ്ക്കണമെന്ന് തീർച്ചയാണോ? ഇത് വീണ്ടെടുക്കാനാവില്ല.',
    agent_tab: 'ഏജന്റ് ഷീൽഡ്', agent_hint: 'നിങ്ങളുടെ AI ഏജന്റ് വായിക്കുന്ന ഏത് ഫയലും പേസ്റ്റ് ചെയ്യുക — പ്രോംപ്റ്റ് ഇൻജെക്ഷൻ, അദൃശ്യ യുണികോഡ് പേലോഡ്, അപകടകരമായ ഹുക്കുകൾ എന്നിവ പരിശോധിക്കുന്നു.', agent_clean: 'വൃത്തിയായത് — നിങ്ങളുടെ ഏജന്റിന് സുരക്ഷിതം', agent_critical: 'വളരെ അപകടകരം — ഈ ഫയൽ വിശ്വസിക്കരുത്'
  }
};
